### ISSUE TITLE
未在训练集出现，只在验证集中出现的新闻是怎么得到它的嵌入向量的？

### ISSUE THREAD

**Issue by Lxhnnn** [yusanshi/NewsRecommendation#10]

**Comment by yusanshi** [comment]
因为这些方法都是 content-based 的推荐，所以直接用 news encoder 根据新闻的内容来获得 embedding 就好了

**Comment by yusanshi** [comment]
This issue will be closed because it has been inactive for some days. You may reopen it if necessary.
