### ISSUE TITLE
MIND测试集的impression没有标签，导致评估无法进行

### ISSUE THREAD

**Issue by Kevin9780** [yusanshi/NewsRecommendation#11]
您好，学习了您的代码，但在evaluate.py中报错了。因为测试集的impression没有标签，导致第292行：
        y = [int(news[0].split('-')[1]) for news in minibatch['impressions']]
提取不出真实的标签y，因为测试集里没有。
这里跟您讨论一下我的理解对不对。

**Comment by yusanshi** [comment]
对的现在 MIND 主办方发布的 test set 确实没有 label，已经有人给 MIND 提过 issue 但还没有回：<https://github.com/msnews/MIND/issues/8>...

建议你在那个 issue 上催一催，或者给他们发邮件催一催

**Comment by Kevin9780** [comment]
好的，谢谢！
