### ISSUE TITLE
请问模型入参的是什么

### ISSUE THREAD

**Issue by auuuu45** [yusanshi/NewsRecommendation#14]
作者你好，在使用这个代码中的模型预测推荐结果的时候，请问模型的入参形式是什么呢，返回的向量用什么解析呢，十分感谢

**Comment by yusanshi** [comment]
您好，这个问题请自行通过调试工具（或print大法）分析 <https://github.com/yusanshi/NewsRecommendation/blob/master/src/train.py#L184-L208> 和 <https://github.com/yusanshi/NewsRecommendation/blob/master/src/evaluate.py#L272-L292>。

**Comment by yusanshi** [comment]
[issue-robot] This issue will be closed because it has been inactive for some days. You may reopen it if necessary.
