### ISSUE TITLE
Preprocessing error reporting

### ISSUE THREAD

**Issue by 1607722534** [yusanshi/NewsRecommendation#19]
Preprocessing error reporting：
Parse ./data/train/news.tsv
malloc(): invalid next size (unsorted)
已放弃 (核心已转储)

Is it the code or the environment?

**Comment by yusanshi** [comment]
I'm not sure but looks like a out-of-memory error?

What's the capacity of the memory? Please check the available memory while running the script. And if it runs out of memory, one possible solution would be enlarging the swap size.

**Comment by 1607722534** [comment]
I use two kinds of servers. The memory occupancy rate is less than 3%, and the cup occupancy rate is 100%.

**Comment by yusanshi** [comment]
Could you find out on which line of code the error occurs? (e.g., use debugging tools, or many `print`)

**Comment by 1607722534** [comment]
Resource punkt not found.   
Please use the NLTK Downloader to obtain the resource:

**Comment by yusanshi** [comment]
> Resource punkt not found.
> Please use the NLTK Downloader to obtain the resource:

Please refer to <https://github.com/joosthub/PyTorchNLPBook/issues/14> or <https://stackoverflow.com/questions/4867197/failed-loading-english-pickle-with-nltk-data-load>.

PS: you can try searching it with search engines first. See [this](https://lmbtfy.tk/?q=UmVzb3VyY2UgcHVua3Qgbm90IGZvdW5kLiBQbGVhc2UgdXNlIHRoZSBOTFRLIERvd25sb2FkZXIgdG8gb2J0YWluIHRoZSByZXNvdXJjZQ==), [this](https://googlethatforyou.com?q=Resource%20punkt%20not%20found.%20Please%20use%20the%20NLTK%20Downloader%20to%20obtain%20the%20resource) and [this](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md). (No offense.)

**Comment by 1607722534** [comment]
I got the preprocessed files. Thank you for your patient reply. My undergraduate is not a computer, so my code ability is too poor.
(╥﹏╥)

**Comment by yusanshi** [comment]
My pleasure. 😁
