### ISSUE TITLE
KeyError: 'early_stop_value'

### ISSUE THREAD

**Issue by DoubleZk** [yusanshi/NewsRecommendation#24]
训练的时候遇到这个bug，请问您知道咋改吗
Traceback (most recent call last):
  File "src/train.py", line 294, in <module>
    train()
  File "src/train.py", line 148, in train
    early_stopping(checkpoint['early_stop_value'])
KeyError: 'early_stop_value'

**Comment by yusanshi** [comment]
你 load 的是哪里的 checkpoint 呀

**Comment by DoubleZk** [comment]
> 你 load 的是哪里的 checkpoint 呀

load的是README中给出的Checkpoints...是不是我load错了哈哈哈

**Comment by yusanshi** [comment]
哦哦那你 load 的是以前的 README 里面的 checkpoint 吧，后来代码改了，一方面 model 的代码有修改，另一方面 checkpoint 里面的内容也变了，所以我就把 README 里面的 checkpoint 链接去掉，改成 https://drive.google.com/open?id=TODO 了，抱歉哈～

所以现在相当于没有 checkpoint 了，只能自己训练了   :)

**Comment by DoubleZk** [comment]
> 哦哦那你 load 的是以前的 README 里面的 checkpoint 吧，后来代码改了，一方面 model 的代码有修改，另一方面 checkpoint 里面的内容也变了，所以我就把 README 里面的 checkpoint 链接去掉，改成 https://drive.google.com/open?id=TODO 了，抱歉哈～
> 
> 所以现在相当于没有 checkpoint 了，只能自己训练了 :)

好滴 谢谢您 感谢回复！
