### ISSUE TITLE
关于train.py中标签y的疑问

### ISSUE THREAD

**Issue by qq31415926** [yusanshi/NewsRecommendation#27]

**Comment by qq31415926** [comment]
标签y包括1个正样本和K个负样本，为什么都统一初始化为0呢？
`        y = torch.zeros(len(y_pred)).long().to(device)
`

**Comment by yusanshi** [comment]
你好，可以看一下这个 issue <https://github.com/yusanshi/news-recommendation/issues/12#issuecomment-851111096>
