### ISSUE TITLE
Did you remove FIM？

### ISSUE THREAD

**Issue by jiaqinglin** [yusanshi/NewsRecommendation#3]
Can you share your basic results over these models?
I rememberd that there was a FIM implement. But you did not show the results.

**Comment by yusanshi** [comment]
> Did you remove FIM?

Yes I found there are some errors in my implementation but I have no time to fix it. So I just removed it. You can view it in the commit history.

> Can you share your basic results over these models?

Months ago, I tested all the methods on MIND small dataset and shown the results in `README.md`. However, I have made some small changes to the code and I began to use MIND large dataset. So I removed the outdated results. Sorry but I haven't tested on the new code and new dataset.

**Comment by Veason-silverbullet** [comment]
Hi, @yusanshi ,

Many thanks for your code! Can you share your finding of FIM? Is it comparable to other strong baselines,i.e., NRMS/NAML? I doubt its performance as my implementation of FIM cannot achieve the expected performance.

**Comment by yusanshi** [comment]
Hi @Veason-silverbullet 

Yes, my implementation for FIM didn't work well too. Not knowing whether there are some errors with my code I just removed it  :(
