### ISSUE TITLE
有关于batch_size的问题

### ISSUE THREAD

**Issue by wjx0110** [yusanshi/NewsRecommendation#31]
你好，我想问问你的代码里面batch_size的大小可以更改吗？还是说128已经是测试过以后更合适的值呢？

**Comment by yusanshi** [comment]
哈哈没怎么测试，你可以 16 32 64 128 256 ... 这样测一测

**Comment by wjx0110** [comment]
你好，我想问问你train.py里面为什么每1000批以后要再计算一下？？这里有点不太明白

**Comment by yusanshi** [comment]
可以说的更清楚一些吗？具体指哪行代码呢？

**Comment by wjx0110** [comment]
![mmexport1648962325059](https://user-images.githubusercontent.com/70767250/161459655-909c1ca7-ade9-494a-8a3d-53b9546fb51f.jpg)
就是这行代码？我不懂为什么1000batch之后要重新计算一下验证集

**Comment by yusanshi** [comment]
你好，主要是用于 Early stopping

https://github.com/yusanshi/news-recommendation/blob/master/src/train.py#L260-L277

**Comment by wjx0110** [comment]
我想问问evaluate.py里面为什么还要有calculating vectors for news这些呢？在train.py里面不是已经计算过了吗？不是保存到ckpt文件里了嘛？直接计算auc不可以吗？

**Comment by yusanshi** [comment]
你好新的问题请开新 issue   #34
