### ISSUE TITLE
测试集

### ISSUE THREAD

**Issue by whxhx** [yusanshi/NewsRecommendation#32]
你好，MIND large测试集是没有标签吗？那评估的时候只能用验证集评估吗？需要负采样什么的吗？我直接预测算的准确度很低很低

**Comment by yusanshi** [comment]
你好请参考 https://github.com/yusanshi/news-recommendation/issues/29#issuecomment-1070034286

**Comment by whxhx** [comment]
非常感谢您~~那可以用train作为训练集，dev作为测试集吗，不设置验证集。或者干脆自己划分数据集可以吗？

**Comment by yusanshi** [comment]
哈哈当然可以，比如 train set 中划出来一部分做 val set，然后现在的 val set 作为 test set。

**Comment by yusanshi** [comment]
只不过这样的话，毕竟没有用官方发布的 test set，没法打榜罢了

**Comment by whxhx** [comment]
好的，感谢您的回答~非常非常非常感谢~~

**Comment by whxhx** [comment]
您好，还有一个问题，我看large数据集上train set, val set, test set是有重叠用户历史纪录的，而small数据集train set和val set没有重叠用户，训练模型的话需要保证是相同的用户吗？

**Comment by yusanshi** [comment]
你好请看下#35~

https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612

**Comment by whxhx** [comment]
好的，明白啦~太感谢您啦，可以怎么支持您呢？

**Comment by whxhx** [comment]
认真看了您发的链接，不好意思，之前不正确地提交issue，之后会按照规范reporting issue的~


|
Shannon
手机：15050591110
***@***.***
|
在2022年4月20日 ***@***.***> 写道：

你好请看下#35~

https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612

**Comment by yusanshi** [comment]
哈哈没关系，感谢支持😄
