### ISSUE TITLE
模型对比

### ISSUE THREAD

**Issue by wjx0110** [yusanshi/NewsRecommendation#36]
既然做模型对比的实验，为什么滤波器的数量和种类不保持一致呢？

**Comment by yusanshi** [comment]
可能原因有：
1. 不同模型有最优的超参数设置，因此调完超参后可能出现超参不一致的情况；
2. 按原始 paper 里面声称的参数来设置的，所以不同方法的不一致；
3. 本 repo 作者随手设置的，没有认真调 :)

**Comment by yusanshi** [comment]
@wjx0110 请记得随手关 issue~
