### ISSUE TITLE
预训练集

### ISSUE THREAD

**Issue by wjx0110** [yusanshi/NewsRecommendation#37]
代码中使用glove训练集进行训练，所以使用glove来提取新闻标题的语义关系吗

**Comment by yusanshi** [comment]
> 代码中使用glove训练集进行训练

你这句话有些指代不清晰。

> 所以使用glove来提取新闻标题的语义关系吗

Glove 只是用来初始化词向量的，这一点在 paper 中有说明。

**Comment by wjx0110** [comment]
是的，我想问问使用什么方法提取新闻的语义特征，word2vec吗？

**Comment by yusanshi** [comment]
没有用到 word2vec；请看各个 paper 的 news encoder 部分

**Comment by wjx0110** [comment]
那你是怎么将单词转化为词向量的呢？在DKN模型里面

**Comment by yusanshi** [comment]
word 建立词典，然后建立 embedding 表（torch 中的 `nn.Embedding`），embedding 表使用 Glove 初始化（Glove 中没有的随机初始化）

**Comment by wjx0110** [comment]
![IMG_20220426_164553](https://user-images.githubusercontent.com/70767250/165260693-74869b3f-774a-4bba-90b5-77c617e39f7e.jpg)
这里是将不存在实体随机初始化，存在的设为正常值吗？

**Comment by yusanshi** [comment]
是的。

请使用截图而不是拍照；或是直接给出具体代码的链接。
请一个问题开一个 issue。
请阅读 <https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md>。
