### ISSUE TITLE
去知识图谱的

### ISSUE THREAD

**Issue by wjx0110** [yusanshi/NewsRecommendation#38]
你好我想问问你这个实验可以去知识图谱吗做个消融实验吗？可以教教我方法吗？

**Comment by yusanshi** [comment]
不好意思，这种代码修改需求请自行看代码理解 :)



请阅读 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md。
你之前的issue我已经给你发过这个了，但是你好像并没有读。
