### ISSUE TITLE
实体上下文嵌入

### ISSUE THREAD

**Issue by wjx0110** [yusanshi/NewsRecommendation#39]
怎么没有处理实体关系呢？没有处理实体关系的代码诶

**Comment by yusanshi** [comment]
抱歉没太懂你的意思，可以说的更详细点吗

**Comment by wjx0110** [comment]
我的意思是你这篇用的是单词向量嵌入和实体向量嵌入，没有加上实体关系的向量嵌入，可是论文里面是有实体关系向量嵌入的

**Comment by wjx0110** [comment]
所以我想问问你是没有写实体关系向量嵌入的这部分代码吗？

**Comment by yusanshi** [comment]
你说的是这里的 context embedding 吧：
https://github.com/yusanshi/news-recommendation/blob/master/src/model/DKN/KCNN.py#L32-L40

数据集没有提供预训练好的 context embedding，只有预训练好的 entity embedding，所以这里的 context embedding 只能随机初始化。

**Comment by wjx0110** [comment]
我看到数据集里面有relation.vec这个实体关系嵌入的文件，你后面pretrained_context_embedding说是有在train里面形成这个文件，所以数据集本来就有实体和词向量的预训练文件，不是代码生成的是吗？我下载太久了忘记数据集里面原来的文件有哪些了不是很清楚，我以为也有关系的预训练文件呢。

**Comment by wjx0110** [comment]
我看到原数据集里面有relation embedding.vec关系嵌入的文件，不知道你有没有考虑加入关系嵌入向量呢？

**Comment by wjx0110** [comment]
context embedding是什么？use context我一直理解的是实体上下文的嵌入向量

**Comment by yusanshi** [comment]
> 我看到数据集里面有relation.vec这个实体关系嵌入的文件

哦我刚检查了下，确实是的。我之前写代码的时候还没有这个文件所以当时数据预处理部分就没有处理它。这个文件估计是 MIND 后来给加上了。

抱歉我最近比较忙，也好久没接触这个了，没空做这个了。

> context embedding是什么?

DKN paper 里面有介绍的。

**Comment by yusanshi** [comment]
请阅读 https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md。

抱歉这是我第三次给你发这个了。请仔细阅读《提问的智慧》。请尽可能提问一些高质量的问题，而不是像“context embedding是什么?”这种读了 DKN paper 就知道的东西。以及，请不要再尝试通过私人邮件问东西了。
