### ISSUE TITLE
news abstract

### ISSUE THREAD

**Issue by TJ2364** [yusanshi/NewsRecommendation#4]
In news.tsv, I noticed that the abstract is not a paragraph of text, but a URL, therefore，is it wrong to directly use the tokenizer method in the code to process the abstract?  What should I do to get a complete abstract？What's more, if you have a complete news.tsv, is it convenient to share it?

**Comment by yusanshi** [comment]
Sorry but I checked the code and I don't think it is wrong.

https://github.com/yusanshi/NewsRecommendation/blob/master/src/data_preprocess.py#L99-L106

From <https://github.com/msnews/msnews.github.io/blob/master/assets/doc/introduction.md>:

### news.tsv

The docs.tsv file contains the detailed information of news articles involved in the behaviors.tsv file.
It has 7 columns, which are divided by the tab symbol:

* News ID 
* Category 
* SubCategory
* Title
* Abstract
* URL
* Title Entities (entities contained in the title of this news)
* Abstract Entities (entites contained in the abstract of this news)


> What's more, if you have a complete news.tsv, is it convenient to share it?

I use `news.tsv` downloaded from https://msnews.github.io/#getting-start and it seems enough.

**Comment by TJ2364** [comment]
@yusanshi 

Thank you very much for your reply. I think I mistook the abstract for the title, and please excuse  me for causing you trouble.
