### ISSUE TITLE
推荐算法

### ISSUE THREAD

**Issue by wjx0110** [yusanshi/NewsRecommendation#41]
你好，我想问一下推荐算法为用户推荐，应该会有一个推荐的结果啊？会显示给用户推荐了哪几条新闻或者是哪个类别的新闻啊？为什么只有AUC这些评价指标呢？

**Comment by yusanshi** [comment]
显示具体推荐哪些新闻对衡量推荐系统性能意义不太，所以我们只关注 AUC 这类 metrics。

在实际应用中，我们对候选新闻打分，从高往低排，能为用户显示几条我们就取前几条显示给用户。
