### ISSUE TITLE
the version of the environment configuration

### ISSUE THREAD

**Issue by tct816** [yusanshi/NewsRecommendation#45]
Can you provide the version of the environment configuration? thank you

**Comment by yusanshi** [comment]
Sorry but I don't have that... What's the problem you're having?

**Comment by tct816** [comment]
When I was configuring the virtual environment, I didn't know how to install torch, etc., because in the requirement file, you only explained what package was needed, but didn't say the version number.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yusanshi/news-recommendation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月18日(星期六) 中午1:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yusanshi/news-recommendation] the version of the environment configuration (Issue #45)





 
Sorry but I don't have that... What's the problem you're having?

**Comment by yusanshi** [comment]
Just install the latest version, I believe

**Comment by tct816** [comment]
Thank you for your answer


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yusanshi/news-recommendation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月18日(星期六) 下午2:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yusanshi/news-recommendation] the version of the environment configuration (Issue #45)





 
Just install the latest version, I believe

**Comment by tct816** [comment]
Sorry to bother you again, I have downloaded the data you provided. I would like to know how you processed the txt file to get the tsv file in your code.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yusanshi/news-recommendation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月18日(星期六) 晚上11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yusanshi/news-recommendation] the version of the environment configuration (Issue #45)





 
Closed #45 as completed.
