### ISSUE TITLE
复现DKN模型AUC不理想以及与知识图谱的联系问题

### ISSUE THREAD

**Issue by DW934** [yusanshi/NewsRecommendation#48]
您好，非常感谢您的代码，写的非常清晰！我遇到了几个问题：
1.我运行了您代码中的DKN模型，其中在data_process.py中没有使用glove词向量进行生成pretrained_word_embedding.npy，复现的结果显示AUC=0.5597，效果十分不理想，想问下这个结果是正常的吗？
2.另外，我看到您的代码中并没有任何和知识图谱嵌入相关的内容，想确认下您的代码是单纯复现了DKN的结构，并没有考虑在embedding时与知识图谱相结合吗？这个也是导致结果与DKN原论文存在差距的原因之一吗？
非常感谢！

**Comment by yusanshi** [comment]
"其中在data_process.py中没有使用glove词向量进行生成pretrained_word_embedding.npy"这个应该是有的，在具体代码里也是有 使用的：  https://github.com/yusanshi/news-recommendation/blob/master/src/model/DKN/KCNN.py#L23-L24
AUC低，这个可能的原因太多了，抱歉我也不清楚

DKN的知识图谱，对的代码里没有用，因为我没有知识图谱相关的信息，“这个也是导致结果与DKN原论文存在差距的原因之一吗” 感觉有道理

**Comment by DW934** [comment]
感谢您及时的回复！我上面提到的"其中在data_process.py中没有使用glove词向量进行生成pretrained_word_embedding.npy"是说我在复现时没有使用glove词向量去生成pretrained_word_embedding.npy文件，不是说您的代码里缺少这个部分，我会再尝试使用词向量后的AUC会不会提高。感谢您的指点！
