### ISSUE TITLE
Question about clicked_news selection

### ISSUE THREAD

**Issue by beanandrew** [yusanshi/NewsRecommendation#50]
First of all, thank you very much for your work.

I noticed that in the file `news-recommendation/src/dataset.py`, you truncate and select the first `num_clicked_news_a_user` clicks as the user's clicked news. I would like to ask why you chose to select the first clicks instead of the last clicks?

```python
    def __getitem__(self, idx):
        item = {}
        row = self.behaviors_parsed.iloc[idx]
        if 'user' in self.config.dataset_attributes['record']:
            item['user'] = row.user
        item["clicked"] = list(map(int, row.clicked.split()))
        item["candidate_news"] = [
            self.news2dict[x] for x in row.candidate_news.split()
        ]
        item["clicked_news"] = [
            self.news2dict[x]
            for x in row.clicked_news.split()[:self.config.num_clicked_news_a_user]
        ]
```

**Comment by yusanshi** [comment]
Yes I believe your're right, should use the most recent values. I really don't know why I could write that...

**Comment by yusanshi** [comment]
Since the repo is written a few years ago, I have forgotten many details and don't have the time to update it. You can fix it and compare the results. If you have time and are willing to do, you can propose a PR. Sorry but I really don't have the time...

**Comment by beanandrew** [comment]
Thank you for your answer, I will try to fix it.
