### ISSUE TITLE
Abnormal performance of NAML

### ISSUE THREAD

**Issue by Veason-silverbullet** [yusanshi/NewsRecommendation#7]
Hi, @yusanshi

I have a puzzle about the performance of NAML. 

I found that NAML significantly outperforms LSTUR and NRMS by a large margin. The same pattern was also found in my implementation code of NAML, LSTUR, and NRMS. I wonder whether you know the reason? The paper claimed that NAML is suboptimal compared to LSTUR and NRMS (https://www.aclweb.org/anthology/2020.acl-main.331.pdf).

Many thanks!

**Comment by yusanshi** [comment]
Because of additional information (i.e., category, subcategory, abstract...)?

Just a guess but I think it's worth a try 😁(e.g., only use the title in NAML, add category information to NRMS...)

**Comment by yusanshi** [comment]
As for the results in the paper, I don't know... It may because of the difference in implementations but we don't know the code they use🤣

**Comment by Veason-silverbullet** [comment]
@yusanshi 
Your guess is right! I wrote an email to the MIND team and just got the response for this issue. Here is part of quotation of their response:

> "While, in the MIND paper, for fair comparison with other methods, only news title is used in NAML. We think this is the reason that NAML performs much better than NRMS and LSTUR in your experiments while not in the MIND paper."

Thanks for your reply. This issue can be closed.
