### ISSUE TITLE
I want to know what the additive attention does？

### ISSUE THREAD

**Issue by bxcxa** [yusanshi/NewsRecommendation#9]
because i find in other place that the additive attention is use to score the alignment of two word ,but in this,it just accept one vector ,and then sent to forward network.could you explain it specifically ?
![image](https://user-images.githubusercontent.com/25433706/104032370-0c54cf00-5209-11eb-9c8a-20ca1fcd916f.png)

**Comment by yusanshi** [comment]
This module is based on [NAML](https://arxiv.org/abs/1907.05576) paper.
```python
class AdditiveAttention(torch.nn.Module):
    """
    A general additive attention module.
    Originally for NAML.
    """
```
![image](https://user-images.githubusercontent.com/36265606/104158285-f8d37f00-5427-11eb-8270-bd42e020da44.png)

It accepts a list of candidates vectors and outputs a weighted combination of the vectors (i.e. $ s = \alpha1 s_1 +  \alpha2 s_2 ... \alpha n s_n $). In other words, input shape: `l, d`, output shape: `d`.

As for the alignment scores computed by the formula you posted, I believe they are the same things with \alpha1, \alpha2, \alpha n. Just the weights for linear combination.

**Comment by bxcxa** [comment]
好家伙，以为是个歪果仁，没想到是校友😂
